### ISSUE TITLE
As a/an authenticated user, I want to submit a session at BADCAMP so that I can get my session evaluated.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#10]
**Story ID:** 10

# Notes

# Acceptance Criteria
Speaker registration should be easy to find and should allow user to submit: their name, an unlimited amount of cospeakers, a proposed topic/theme, a title for their presentation, and an abstract.

**Comment by hrod** [comment]
NOTE: This ticket is in discovery only.

**Comment by hrod** [comment]
Note: write copy to tell people how to propose a session.

**Comment by sean-e-dietrich** [comment]
Page for this already exists. /sessions.
The PR for this was already approved just needs to have copy written for the page.

**Comment by AnneStefanyk** [comment]
confirmed!
