### ISSUE TITLE
Design / Pattern Library

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#101]
Create design mockups for library of components to be used throughout the site and achieve consistency throughout. NOT a Pattern Lab implementation, but kinda.

**Comment by hrod** [comment]
The design part of this is underway for Sprint 3.

**Comment by hrod** [comment]
<img width="715" alt="badcamp-2017-partial-style-tile" src="https://user-images.githubusercontent.com/4369591/28097127-9e4ea548-6662-11e7-926d-658caa3723e8.png">
