### ISSUE TITLE
Config Import on live following 5-30 deployment

### ISSUE THREAD

**Issue by rbayliss** [badcamp/badcamp-2017-Sprint-Planning#103]
Looks like there's a lot of stuff overridden following the deployment this afternoon.  @populist - I think you said the import is failing because the profile is being changed?
![screen shot 2017-05-30 at 4 23 11 pm](https://cloud.githubusercontent.com/assets/654407/26603293/4cff8b14-4554-11e7-9e2c-c966b525ad5c.png)

**Comment by populist** [comment]
The issue with the import was some of the UUID desinations in the YML files were missing. I went ahead and refreshed the configuration and things are now importing cleanly.
