### ISSUE TITLE
/news page should only have short summary

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#106]
Something like 500-600 characters with Read More

Also needs menu link.

**Comment by hrod** [comment]
Looks great! Can we just remove the "submitted by Anne" bit?

**Comment by hrod** [comment]
<img width="1090" alt="screen shot 2017-07-11 at 6 10 30 pm" src="https://user-images.githubusercontent.com/4369591/28097317-4a748b3e-6664-11e7-8979-b306ba1adbc0.png">

**Comment by hrod** [comment]
<img width="1096" alt="screen shot 2017-07-11 at 6 14 57 pm" src="https://user-images.githubusercontent.com/4369591/28097429-f09ebb2e-6664-11e7-8083-7f9bea699796.png">
