### ISSUE TITLE
Add blog RSS feed to Drupal Planet

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#108]
@carsonblack commented on [Thu May 18 2017](https://github.com/badcamp/badcamp-2017/issues/29)

Use this form to request that our Drupal Planet blog feed be added
https://www.drupal.org/node/add/project-issue/content?component=Planet%20Drupal&categories=task&title=Add%20%5Byour-domain%5D%20to%20Planet%20Drupal&body=Blog%20name%3A%0ADrupal-Planet%20tagged%20feed%20URL%3A

**Comment by sean-e-dietrich** [comment]
In order to add blog to Drupal Planet 2 posts must be created and tagged with Drupal Planet tag.

Standards for adding posts are here: https://www.drupal.org/drupalorg/docs/content/planet-drupal

**Comment by hrod** [comment]
Thanks @sean-e-dietrich ! @eskimoYogi has added two blog posts now.

**Comment by sean-e-dietrich** [comment]
@eskimoYogi @hrod these have to be 2 blog posts with the Drupal Planet tag. So, we can take that feed and send it to Drupal.org

**Comment by AnneStefanyk** [comment]
@sean-e-dietrich we have two posts tagged with Drupal Planet now: https://2017.badcamp.net/news

**Comment by sean-e-dietrich** [comment]
Has been submitted for review by Drupal.org

https://www.drupal.org/node/2906693
