### ISSUE TITLE
Second level menu design and theming

### ISSUE THREAD

**Issue by hrod** [badcamp/badcamp-2017-Sprint-Planning#114]
Second level menu items need to be designed and themed out: 
https://2017.badcamp.net/

**Comment by hrod** [comment]
Implement second level menu from Foundation.

**Comment by bixgomez** [comment]
Here is an idea for a submenu.  I would like discussion and approval before I proceed to implement it.

![submenu design idea](https://user-images.githubusercontent.com/292571/28508460-f2c70b4c-6fef-11e7-835e-3c68158a181b.png)

**Comment by sean-e-dietrich** [comment]
Once deployed the menu items will need to have the `Show as expanded` checked so that their children will end up showing up and a true dropdown will be working.

**Comment by bixgomez** [comment]
Pull Request: https://github.com/badcamp/badcamp-2017/pull/84
