### ISSUE TITLE
As a visitor to the site viewing a user profile it should have an attractive layout so that I am not repulsed by its simplicity.

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#122]
Acceptance Criteria:

- Layout using Foundation media object

- Picture on the left, info on the right
- I did this to a point, but I'm sure it could be better.

**Comment by jlandfried** [comment]
@carsonblack @sean-e-dietrich could one of you guys take a look at the PR attached to this when you get some time?
