### ISSUE TITLE
As a/an anonymous user, I want to receive a notification when I submit a session so that know that my session went through ok.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#13]
**Story ID:** 13

# Notes

# Acceptance Criteria
Upon submitting speaker registration form, the user will receive a message that says their submission was successful and also a corresponding email in their inbox.

**Comment by sean-e-dietrich** [comment]
This should only be an authenticated user and not Anon.
