### ISSUE TITLE
Profile Field edits

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#147]

**Comment by AnneStefanyk** [comment]
a) https://www.evernote.com/l/AQdIJIkImVNKsblukuWLI8cBIbSd2UmQHRE
- This 'add another' is broken - remove this 

b) Add the following fields
- Organization Website 
- Twitter
- Facebook

c) Move Bio field up to below name

**Comment by carsonblack** [comment]
Also going to add in not letting user set timezone. That's just nonsense that we won't pay attention to anyway.

**Comment by AnneStefanyk** [comment]
approved - thank you
