### ISSUE TITLE
As a/an administrator, I want to mark a session as accepted so that I can populate the schedule .

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#15]
**Story ID:** 15

# Notes

# Acceptance Criteria
There is a boolean on the session node that administrators can check as to whether a session has been accepted or rejected.

**Comment by sean-e-dietrich** [comment]
This should already be apart of:

https://github.com/badcamp/badcamp-2017-sprint-planning/issues/48

**Comment by sean-e-dietrich** [comment]
@carsonblack this should already be in place. In each session there is an administration tab that contain whether the session was just proposed or if it was approved.
