### ISSUE TITLE
Convert session track from dropdown to checkboxes

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2017-Sprint-Planning#153]
On Session Node Add change Session track dropdown from dropdown to checkboxes and allow for multiple tracks

**Comment by sean-e-dietrich** [comment]
This ended up being apart of the same PR as https://github.com/badcamp/badcamp-2017-Sprint-Planning/issues/149

**Comment by AnneStefanyk** [comment]
confirmed
