### ISSUE TITLE
As a BADCamp Organizer I want comment on an individual Contact Form message so other organizers can see what was done about the request.

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#158]

**Comment by sean-e-dietrich** [comment]
Each webform submission has the ability to add notes to it. This is located in the Webform Results page and each record has a notes icon:

https://pr-contact-badcamp-2017.pantheonsite.io/admin/structure/webform/manage/contact/results/submissions

It is the Paper Icon which is to the right of the star icon.
