### ISSUE TITLE
Fix the SWAG sizing message (spelling of because)

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#167]
"Because of your generosity you are being rewarded with magnificent SWAG! Please choose your size as this will help BADCamp with orders and we will do our best to make sure you get the size you select. Thank you!"

**Comment by AnneStefanyk** [comment]
"Because" is still misspelled, other than that - approved. Thanks

**Comment by AnneStefanyk** [comment]
@carsonblack Becuase is still misspelled like that - not sure where to edit  @carsonblack

**Comment by AnneStefanyk** [comment]
https://www.evernote.com/shard/s10/sh/048d9d38-c0be-4457-a1f0-66e85c222aae/f3f2c7781c3a4633
