### ISSUE TITLE
Fix name look up display for session speaker on add session

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#168]
Add Session: Fix name look up display for session speaker
See: https://www.evernote.com/l/AQfIhqggMtBAI5gw7vZ66x346iu8ncTLnzE

**Comment by sean-e-dietrich** [comment]
@eskimoYogi I'm unable to reproduce this on the test site in either safari or chrome.

**Comment by AnneStefanyk** [comment]
me either
