### ISSUE TITLE
Session Description field label showing twice

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#169]
Session Description showing twice: 
https://www.evernote.com/l/AQdIbqtPpudNar4m27JdUrNetY_f1uwJkrw

**Comment by carsonblack** [comment]
This is caused by the field group and field name being labeled the same. We should keep the consistency of the labeling for the group so I just changed the field label to just "Description" should look a little less weird.

**Comment by AnneStefanyk** [comment]
confirmed
