### ISSUE TITLE
Flow for Anonymous Users to Submit Sessions by Registering

### ISSUE THREAD

**Issue by AnneStefanyk** [badcamp/badcamp-2017-Sprint-Planning#172]
We need a button to ‘Submit Your Session Proposal Today’ to prompt to log in or register, then redirect them upon log in etc to the submit session form 

https://test-badcamp-2017.pantheonsite.io/session-submissions

 (the link I currently created is not a good solution)

**Comment by carsonblack** [comment]
I believe this Pull Request could be the solution to this: https://github.com/badcamp/badcamp-2017/pull/96
I will redirect the Access denied page to a login page.

**Comment by carsonblack** [comment]
Also, I made your link a button (add the classes "button" and "large" )

**Comment by carsonblack** [comment]
OK, that PR got merged.

**Comment by carsonblack** [comment]
Yep that works! it's on Test environment now. Going to close this Issue
