### ISSUE TITLE
As a Camp organizer I need a report of people who need to receive SWAG so that I can easily mark them as having received it when they pick it up. 

### ISSUE THREAD

**Issue by carsonblack** [badcamp/badcamp-2017-Sprint-Planning#179]
View of Payments that have not been refunded.
Display: Table (preferably with some kind of bulk operations or checkbox to mark received) & CSV export 
Fields:
First Name
Last Name
Donation Level (Amount)
Received - need to add this field to the payment entity
T-shirt Type
T-Shirt Size
Hoodie Size
Portable Charger (Y/N) Show yes if they are supposed to get one of these.

**Comment by AnneStefanyk** [comment]
@carsonblack @sean-e-dietrich we are in the mode to find out what distribution of Swag to order 

Putting this into sprint 12
