### ISSUE TITLE
Proposed Sessions page has a blank block - delete?

### ISSUE THREAD

**Issue by scalico** [badcamp/badcamp-2017-Sprint-Planning#188]
Proposed Sessions page has a blank block below the menu. Can it be deleted?
https://2017.badcamp.net/sessions

**Comment by scalico** [comment]
I think the solution to this problem is to change the layout position of this block from Highlighted to Disabled. It seems to be configured only to appear on the /sessions page, but I'm not sure if it appears on any other pages. (One curiosity is that the block shows as a blank space, even though I saw somewhere that it has lorem ipsum text in it.)
Now that the site is live, I'm hesitant to make these changes without a second opinion. I was going to try it on the test site, but I don't have the permissions there to do anything.

**Comment by AnneStefanyk** [comment]
cool - thanks Sean
https://pr-session-badcamp-2017.pantheonsite.io/sessions

**Comment by AnneStefanyk** [comment]
cool - thanks Sean
https://pr-session-badcamp-2017.pantheonsite.io/sessions
