### ISSUE TITLE
Summit organizer user name links are incorrect

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#202]
# Issue
When reading summit pages, hyperlinked organizer names take you to a login prompt + donation redirect.

# Steps to Reproduce
1. Log out of the BADCamp website
2. Go to https://2017.badcamp.net/event/summit/front-end-summit
3. Click on _jasonsavino_
4. Link takes you to https://2017.badcamp.net/user/login?destination=/donate

**Comment by sean-e-dietrich** [comment]
Pending PR: https://github.com/badcamp/badcamp_stripe_payment/pull/8
