### ISSUE TITLE
Page legibility needs improvement sitewide

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#203]
# Issue
Line lengths and font sizes/spacing are very difficult to read throughout the site. The treatment of categorical icons is also cramped at the top.

I am looking at summit pages specifically.
https://2017.badcamp.net/event/summit/front-end-summit

# Proposed solution
I recommend the following CSS changes to improve legibility throughout the site for these content heavy pages. I've conferred with @kwmurphy, the designer, and she has approved the results.

 ```
#block-badcamp2017-content > article.contextual-region {
    max-width: 800px;
    margin: 0 auto;
    font-size: 1.25rem;
}
```

```
span.category-icon {
    font-size: 1rem;
    margin: 1.25rem 0 2rem 0;
    line-height: 1.3;
    display: inline-block;
    background: aliceblue; // or a theme color...
    padding: 0 .4rem;
}
```

**Comment by sean-e-dietrich** [comment]
The following is also included in this: https://github.com/badcamp/badcamp-2017-Sprint-Planning/issues/199
