### ISSUE TITLE
News Page - delete links (4 tags) to Drupal Planet

### ISSUE THREAD

**Issue by scalico** [badcamp/badcamp-2017-Sprint-Planning#214]
Each item on the News page has Drupal Planet links after it. The Drupal Planet page has mostly duplicate items on it. My recommendation is to Unpublish the Drupal Planet Page and (if that doesn't do it) get rid of the tag links.
https://2017.badcamp.net/news
https://2017.badcamp.net/drupal-planet

**Comment by sean-e-dietrich** [comment]
@scalico we can't disable the `drupal-planet` page it is a taxonomy page that is auto generated. We also cannot get rid of the tag links because we need them in order to show the pages on Drupal.org.
