### ISSUE TITLE
Sponsorship page - add Donate button to Individual sponsorship

### ISSUE THREAD

**Issue by scalico** [badcamp/badcamp-2017-Sprint-Planning#216]
On the Sponsorship page - https://2017.badcamp.net/sponsorship -
all levels of sponsorship and their perks are listed, including the individual sponsorship level. That level should have a Donate button, since you don't really need to have them contacting Anne or Matt.

After puttng a Donate button under the Indiv Sponsor item, then move the line:
**Interested? Please contact anne@badcamp.net or matt@badcamp.net**
between the Indiv level and the $350 level, since it applies to the higher levels only. (Or put that line above the highest level, just after the intro text.)

**Comment by AnneStefanyk** [comment]
@scalico good one! updated https://2017.badcamp.net/sponsorship
