### ISSUE TITLE
Menu items - duplicate pages 

### ISSUE THREAD

**Issue by scalico** [badcamp/badcamp-2017-Sprint-Planning#217]
The following items in the Main Menu link to pages that contain duplicate information. 

Event Details > Community link contains duplicate information that is found in Code of Conduct and Contribution Lounge. **Recommendation: delete Community menu item**

Sponsors > Donate and Sponsors > Individual Sponsorship contain duplicate information. **Recommendation: delete Individual Sponsorship link**

**Comment by AnneStefanyk** [comment]
done
