### ISSUE TITLE
As a/an anonymous user, I want to learn about sponsorship levels so that I can determine the right level of sponsorship for my organization.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#25]
**Story ID:** 26

# Notes

# Acceptance Criteria
Tiered sponsorship offerings are visible and easy to find on the website.

**Comment by hrod** [comment]
Right now, we need a consensus on what we're calling these sponsorship levels and any content updates if needed.

**Comment by shirazd** [comment]
see comment below

**Comment by shirazd** [comment]
- For each sponsorship level, populate the sponsorship name, description, and amount (copy from https://2016.badcamp.net/sponsorship-packages)
