### ISSUE TITLE
As a/an summit coordinator, I want to list sponsors for my summit so that I can make sure sponsors feel rewarded and will be interested in sponsoring in future years.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#30]
**Story ID:** 31

# Notes

# Acceptance Criteria
Ability to link to a Sponsor company and list the sponsor's name/logo in a prominent location.

**Comment by AnneStefanyk** [comment]
@sean-e-dietrich this works, we just need to theme the summit node to show the summit logos vs just the links to the sponsor nodes. 

Thanks!
