### ISSUE TITLE
As a/an attendee, I want to see what summits I'm signed up for so that I can confirm my attendance and prevent myself from accidentally double-booking with a training or another summit.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#33]
**Story ID:** 34

# Notes

# Acceptance Criteria
Text on the summit list and on the individual summit description showing that the logged-in user has registered for the summit. Validation to prevent double-booking (or at least warn of it) would be ideal.

**Comment by sean-e-dietrich** [comment]
User's Schedule can be found on the Profile
