### ISSUE TITLE
As a/an attendee, I want to get detailed directions to the summit venue so that I can get to the summit easily on the day of the event.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#34]
**Story ID:** 35

# Notes

# Acceptance Criteria
Detailed description of the venue complete with address, map, picture, and any necessary details on the location (parking, specific rooms within building/complex, etc.)

**Comment by sean-e-dietrich** [comment]
Directions for the venue can be found on the venue page.
