### ISSUE TITLE
As a/an authenticated user, I want to Enter payment information and have my card charged for an individual sponsorship so that I can pay for an individual sponsorship.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#43]
**Story ID:** 44

# Notes

# Acceptance Criteria
Payment data collected and authorized via Stripe. Messaging displayed on payment complete or declined.

**Comment by carsonblack** [comment]
Current status: This can be done using the badcamp_stripe_payment module. Just need to create a badcamp_donation module to do the following more specific pieces of functionality:

- Create a donate page that has the blocks for the various donation amounts on it (Default content).

- Handle the redirect from account creation to donate page. 

- Messaging that thanks the user for already donating if they already have. This will be helpful if they ever come back to the donate page later.
