### ISSUE TITLE
As a/an anonymous user, I want to view venue details so that I can get a sense of the location and see the events happening there.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#48]
**Story ID:** 49

# Notes

# Acceptance Criteria

1. Content Type (Venue) with the following fields:
- Name (title field)
- Geolocation Field: Install the module: https://www.drupal.org/project/geolocation
- Floor (to keep track of what floor of the building this might be on)
- Room Number/Name (textfield)
- Picture (An actual picture of the building or door of the room) (image field)
Display: 
Full: 
 - Geolocation as a map with a point Zoomed in to at least city level. 
 - Link to Get Directions that would launch map app(?)
 - Picture Float to the right of the list of text information. Collapse below text info on mobile. 
 - All others in a list
Teaser:
 - Title linked to node
 - Thumbnail of photo linked to node
 - Inline Text: RoomName/Number, Floor
 - Link to Get Directions that opens map app

2. Creation of a View with a block displaying related Events:
- Content type: events
- Contextually filtered by content related to the Venue id from path
- Show content teasers
  - Titles should link in teasers to event node

**Comment by hrod** [comment]
@carsonblack to add story information.

**Comment by sean-e-dietrich** [comment]
* Add Map to Venue
* Add Calendar Agenda of Events Associated
* Create Venue Content Type
* Create Event Content Type
- Reference 2016 site for fields
* Create view of events

**Comment by carsonblack** [comment]
See acceptance criteria that have been updated. Let's not have Event content type creation in this one issue as well. I'll put that in another issue.
