### ISSUE TITLE
As a/an anonymous user, I want to be able to fill out a user registration form so that I can register for the camp and get an account on the website..

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#5]
**Story ID:** 5

# Notes
This creates the drupal user and logs them in.

# Acceptance Criteria

Registration form with the following fields:
Username
Email - Confirm Email
Password - Confirm
Drupal.org Username
I would like to volunteer Checkbox
Subscribe to Newsletter checkbox

If checked, subscribe the user to the newsletter on user save.

**Comment by hrod** [comment]
@carsonblack I'm not sure this ticket is ready to be closed.

How would a user register? We need a menu link for Login.

**Comment by carsonblack** [comment]
It's the normal user registration accessed here: https://2017.badcamp.net/user/register. There is a separate issue for the link to be added to the menu that's in the current sprint.
