### ISSUE TITLE
As a/an anonymous user, I want to to have the training options clearly marked for the following information: day and time of training, title, short summary, trainers, level, number of regitrations, remaining registrations, location of training (building and room text),full details of the training, register now link

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#57]
**Story ID:** 65

# Notes
The ONLY THING MISSING AT THIS POINT IS THE REGISTER LINK

Historic listings have looked yucky and are hard to use.

# Acceptance Criteria
Is it accessible and does it have all the info.

**Comment by sean-e-dietrich** [comment]
Currently pending PR for the badcamp_stripe_payment module

https://github.com/badcamp/badcamp_stripe_payment/pull/7
