### ISSUE TITLE
As a/an anonymous user, I want to be able to easily find a link in the menu that links to the registration form  so that I can easily register for the camp.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#6]
**Story ID:** 6

# Notes

# Acceptance Criteria
A link labeled Register appears in the main menu

**Comment by hrod** [comment]
Menu is already there; it's just not currently displayed nor themed.

**Comment by hrod** [comment]
@bixgomez may need to provide guidance on styling.

**Comment by jlandfried** [comment]
@hrod could you check this PR out when you get a chance? The build failed on something unrelated

**Comment by sean-e-dietrich** [comment]
@carsonblack @hrod this is currently not something that can be exported into configuration it doesn't look like. I wonder if we are at a place that we can just place it in the menu on the live environment. 

The only difference is that in Drupal 7 the menu link would hide if the person was already logged in. Therefore, the issue right now would be that the user would see the Register link regardless if they are logged in or not. When they clicked the link logged in though it would direct them to their account.
