### ISSUE TITLE
As a/an anonymous user, I want to view a list of sponsors so that I can thank all the awesome sponsors.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#77]
**Story ID:** 85

# Notes

# Acceptance Criteria
There is a list of all sponsors sorted by tier and shows both their logo, name
Sponsor view should have main menu link .

**Comment by hrod** [comment]
@sean-e-dietrich The view should be accessible from the main menu.

**Comment by sean-e-dietrich** [comment]
@hrod link has been added to main navigation.
