### ISSUE TITLE
As a trainee, when I cancel my training I would like to receive a refund of my registration fee if it is before the cancellation deadline.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#78]
@carsonblack commented on [Mon Mar 27 2017](https://github.com/kanopi/badcamp-zenhub/issues/117)

Commerce / Training registration
Depending on whether we use Eventbrite or Stripe with custom payment we need a way to automatically refund a user who cancels so there is no manual process involved. 

---

@carsonblack commented on [Mon Mar 27 2017](https://github.com/kanopi/badcamp-zenhub/issues/117#issuecomment-289501686)

Relates to #100

**Comment by sean-e-dietrich** [comment]
Contained in the following PR
https://github.com/badcamp/badcamp_stripe_payment/pull/7
