### ISSUE TITLE
Base Drupal 8 Install and Create/Theme Homepage

### ISSUE THREAD

**Issue by hrod** [badcamp/badcamp-2017-Sprint-Planning#79]
Install Drupal 8 and set up homepage.

Acceptance Criteria
Information should be laid out according to mockup and include:
Dates
Location
Summits/Trainings
Sponsors logo

Ignore menu, links, etc. 

Design: https://www.dropbox.com/s/h8dcydgier7nbqi/homepage.psd?dl=0

**Comment by AnneStefanyk** [comment]
Instance has been set up on Pantheon & Heather, Kat, Carson & Hook42 (org) have been added to the dashboard 
http://dev-badcamp2017.pantheonsite.io/
