### ISSUE TITLE
As a/an anonymous user, I want to see a list of all the summits that include when they are so that I can determine which summit I want to attend.

### ISSUE THREAD

**Issue by kwhite** [badcamp/badcamp-2017-Sprint-Planning#8]
**Story ID:** 8

# Notes

# Acceptance Criteria
Summit title, date, brief description for all summits is visible on main summit page

**Comment by sean-e-dietrich** [comment]
Duplicate of https://github.com/badcamp/badcamp-2017-Sprint-Planning/issues/26
