### ISSUE TITLE
Stray Pantheon Link

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2017-Sprint-Planning#90]
When screen is above a certain size it looks like the Pantheon text is showing in the footer.

![screen shot 2017-05-12 at 6 29 06 pm](https://cloud.githubusercontent.com/assets/1564748/26021421/50888234-3741-11e7-80b4-c789d3f0c51e.png)

**Comment by rbayliss** [comment]
This will probably go away once https://github.com/badcamp/badcamp-2017/pull/34 is merged in.
